### ISSUE TITLE
Remove conio.h

### ISSUE THREAD

**Issue by GitHG22** [NixonZ/Cpp-Z#4]
conio.h is an obsolete header file used in DOS systems, and is available in old C++ compilers such as the Borland Turbo C++. It isn't compatible with gcc (which most of us are using) and isn't recommended anyways. An alternative would be to use curses.h .

More discussion here:
http://stackoverflow.com/questions/8792317/why-cant-i-find-conio-h-on-linux
http://stackoverflow.com/questions/3276546/how-to-implement-getch-function-of-c-in-linux
https://www.quora.com/What-is-the-meaning-of-conio-h-in-C++

**Comment by NixonZ** [comment]
conio.h is a header file mostly used by MS-DOS compilers to provide console input and output. Some of its inbuilt functions are:

clrscr() - It is used to clear the screen
cgets() - Reads a string from the keyboard
getch() - Reads a character from keyboard
getche() - Reads a character from keyboard and echoes it to the screen
kbhit() - Determines if a keyboard key was pressed
putch() - Writes a character to the screen
cputs() - Writes a string to the screen

**Comment by GitHG22** [comment]
"MS-DOS Compilers"

**Comment by NixonZ** [comment]
<conio.h> shall be removed;
