### ISSUE TITLE
I am pissed!!!!

### ISSUE THREAD

**Issue by NixonZ** [NixonZ/Cpp-Z#6]
[https://github.com/NixonZ/Cpp-Z/blob/master/Cppfiles/Array-Assignment/1-D/Q1.cpp](url)
The GNU GCC compiler allows multiple declaration but the Turbo shit does not. Officially all my programs are wrong.Well done Turbo(piece of shit)

**Comment by GitHG22** [comment]
GNU GCC compiler allows multiple declaration? How?

**Comment by NixonZ** [comment]
Try it

**Comment by GitHG22** [comment]
Doesn't work

**Comment by NixonZ** [comment]
the scope of the variable should not conflict

**Comment by GitHG22** [comment]
kya bol ra? noobish mein bol

**Comment by NixonZ** [comment]
for(int i=0;i<3;i++)
{.....
}
for(int i=0;..;...)
{...
}
ye  turbo me allowed ni
par gnu gcc me allowed hai
